

class REPL_STATE:
    NONE = 0
    CONNECT = 1
    CONNECTING = 2
    RECEIVE_PING_REPLY = 3
    SEND_HANDSHAKE = 4
    RECEIVE_AUTH_REPLY = 5
    RECEIVE_PORT_REPLY = 6
    RECEIVE_IP_REPLY = 7
    RECEIVE_CAPA_REPLY = 8
    SEND_PSYNC = 9
    RECEIVE_PSYNC_REPLY = 10
    TRANSFER = 11
    CONNECTED = 12

class REPL_SLAVE_STATE:
    NONE = 0
    CONNECT = 1
    CONNECTING = 2
    RECEIVE_PONG = 3
    SEND_AUTH = 4
    RECEIVE_AUTH = 5
    SEND_PORT = 6
    RECEIVE_PORT = 7
    SEND_IP = 8
    RECEIVE_IP = 9
    SEND_CAPA = 10
    SEND_PSYNC = 11
    RECEIVE_PSYNC = 12
    TRANSFER = 13
    CONNECTED = 14
